image: python:latest

default:
  tags:
    - osm

before_script:
  - apt update
  - apt install -y git-lfs

stages:
  - build
  - test

build:
  stage: build
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    - git config user.email "felix.grzelka@hpi.de"
    - git config user.name "ci-bot"
    - git remote add gitlab_origin https://oauth2:$ACCESS_TOKEN@gitlab.hpi.de/kisz/workshops/pre-trained-models-workshop.git
    
    - ./rebase.sh

    - git push -f gitlab_origin solutions/benchmark -o ci.skip # prevent triggering pipeline again
    - git push -f gitlab_origin solutions/backend -o ci.skip # prevent triggering pipeline again
    - git push -f gitlab_origin solutions/docker -o ci.skip # prevent triggering pipeline again

test_benchmark:
  stage: test
  rules:
      - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    - git checkout solutions/benchmark
    - pip install -r requirements.txt
    - pip install -r requirements-dev.txt
    - pytest tests/test_benchmarks.py

test_backend:
  stage: test
  rules:
      - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    - git checkout solutions/backend
    - pip install -r requirements.txt
    - pip install -r requirements-dev.txt
    - pytest
