image: python:latest

# before_script:
#   - python --version ; pip --version  # For debugging
#   - pip install virtualenv
#   - virtualenv venv
#   - source venv/bin/activate

build:
  script:
    - git checkout 

# test:
#   script:
#     - pip install ruff tox  # you can also use tox
#     - pip install --editable ".[test]"
#     - tox -e py,ruff

# run:
#   script:
#     - pip install .
#     # run the command here
#   artifacts:
#     paths:
#       - build/*

# pages:
#   script:
#     - pip install sphinx sphinx-rtd-theme
#     - cd doc
#     - make html
#     - mv build/html/ ../public/
#   artifacts:
#     paths:
#       - public
#   rules:
#     - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

# deploy:
#   stage: deploy
#   script: echo "Define your deployment script!"
#   environment: production

