image: python:latest

default:
  tags:
    - osm

before_script:
  - apt update
  - apt install -y git-lfs
#   - python --version ; pip --version  # For debugging
#   - pip install virtualenv
#   - virtualenv venv
#   - source venv/bin/activate

build:
  only:
    - main
  script:
    - git config user.email "felix.grzelka@hpi.de"
    - git config user.name "ci-bot"
    - git remote add gitlab_origin https://oauth2:$ACCESS_TOKEN@gitlab.hpi.de/kisz/workshops/pre-trained-models-workshop.git
    
    - ./rebase.sh

    - git push -f gitlab_origin solutions/benchmark -o ci.skip # prevent triggering pipeline again
    - git push -f gitlab_origin solutions/backend -o ci.skip # prevent triggering pipeline again

test_benchmark:
  only:
    - main
  script:
    - git checkout solutions/benchmark
    - pip install -r requirements.txt
    - pip install -r requirements-dev.txt
    - pytest tests/test_benchmarks.py

test_backend:
  only:
    - main
  script:
    - git checkout solutions/backend
    - pip install -r requirements.txt
    - pip install -r requirements-dev.txt
    - pytest
