version: "3.9"
services:
  app:
    build: .
    image: whisper-demo
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
      - ~/.cache/whisper:/root/.cache/whisper
    # TODO: expose Port 8000 of the app container to the host
