version: "3.9"
services:
  app:
    build: .
    image: whisper-demo
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
      - ~/.cache/whisper:/root/.cache/whisper
    ports:
      - "8000-8010:8000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
