version: "3.9"
services:
  rabbitmq:
    image: rabbitmq
  app:
    build: .
    image: whisper-demo
    ports:
      - "8000:8000"
  celery-worker:
    image: whisper-demo
    command: celery -A transcribe worker --loglevel=INFO
    environment:
      - TRANSFORMERS_CACHE=/models
    volumes:
      - ./models:/models
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]